const SET_PLAYER_DATA_ACTION = 'SET_PLAYER_DATA_ACTION';
const RESET_USER_ACTION = 'RESET_USER_ACTION';
const SET_BATTLE_BTN_ACTION = 'SET_BATTLE_BTN_ACTION';
const SET_RESTART_BTN_ACTION = 'SET_RESTART_BTN_ACTION';
const SET_USER_REPOS_ACTION = 'SET_USER_REPOS_ACTION';
const SET_USER_SCORE_ACTION = 'SET_USER_SCORE_ACTION';
const RESET_BATTLE_ACTION = 'RESET_BATTLE_ACTION';
const RESET_SCORE_ACTION = 'RESET_SCORE_ACTION';


export { 
    SET_PLAYER_DATA_ACTION, 
    RESET_USER_ACTION, 
    SET_BATTLE_BTN_ACTION, 
    SET_RESTART_BTN_ACTION, 
    SET_USER_REPOS_ACTION, 
    SET_USER_SCORE_ACTION,
    RESET_BATTLE_ACTION,
    RESET_SCORE_ACTION 
};